# Generated by Django 3.1.4 on 2021-01-10 10:55

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Title for article', max_length=500, null=True)),
                ('have_image', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not Sure')], default='not_sure', help_text='Does this article have image or not?', max_length=95)),
                ('username', models.CharField(blank=True, default='Anonymous', help_text='Article written by', max_length=129)),
                ('views', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, choices=[('India', 'India'), ('Cricket', 'Cricket'), ('Sports', 'Sports'), ('World', 'World'), ('Business', 'Business'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Lifestyle', 'Lifestyle'), ('Science', 'Science'), ('Health', 'Health'), ('Education', 'Education'), ('Un-categorised', 'Un-categorised'), ('Newsh', 'Newsh')], default='Un-categorised', help_text='Category for article', max_length=95)),
                ('tags', models.CharField(blank=True, default='', help_text='One word tags', max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, help_text='Slug will be generated automatically from the title of the post', max_length=200, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('table_of_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='Post/post-images')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('year', models.IntegerField(default='0000', help_text='Year of article published')),
                ('month', models.IntegerField(default='00', help_text='Month of article published')),
                ('day', models.IntegerField(default='00', help_text='Day of article published')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Comment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=400, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post_comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
                ('article_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
    ]
