# Generated by Django 3.1.4 on 2021-01-15 05:47

import blog.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Hindi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Title for article', max_length=500, null=True)),
                ('have_image', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not Sure')], default='not_sure', help_text='Does this article have image or not?', max_length=95)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to=blog.models.hindi_post_image_path)),
                ('username', models.CharField(blank=True, default='Anonymous', help_text='Article written by', max_length=129)),
                ('views', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, choices=[('स्टोरीज', 'स्टोरीज'), ('एनालिसिस', 'एनालिसिस'), ('लाइफस्टाइल', 'लाइफस्टाइल'), ('अन्य', 'अन्य')], default='अन्य', help_text='Category for article', max_length=95)),
                ('tags', models.CharField(blank=True, default='', help_text='One word tags', max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, help_text='Slug will be generated automatically from the title of the post', max_length=200, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('table_of_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('year', models.IntegerField(default='0000', help_text='Year of article published')),
                ('month', models.IntegerField(default='00', help_text='Month of article published')),
                ('day', models.IntegerField(default='00', help_text='Day of article published')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.english_post_image_path),
        ),
    ]
