# Generated by Django 3.1.4 on 2021-01-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210115_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_hindi',
            name='english_title_for_slug',
            field=models.CharField(blank=True, default='', help_text='Title in English for article', max_length=500, null=True),
        ),
    ]
