# Generated by Django 3.1.4 on 2021-01-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_hindi_english_title_for_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_hindi',
            name='english_title_for_slug',
        ),
        migrations.AddField(
            model_name='article_hindi',
            name='title_hindi',
            field=models.CharField(blank=True, default='', help_text='Title for article', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article_hindi',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title in English for article', max_length=500, null=True),
        ),
    ]
