# Generated by Django 3.1.4 on 2021-01-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210115_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_hindi',
            name='category',
            field=models.CharField(blank=True, choices=[('स्टोरीज', 'स्टोरीज'), ('एनालिसिस', 'एनालिसिस'), ('लाइफस्टाइल', 'लाइफस्टाइल'), ('अन्य', 'अन्य')], default='अन्य', help_text='Category for article', max_length=95),
        ),
    ]
