# Generated by Django 3.1.4 on 2021-01-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210115_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_hindi',
            name='category',
            field=models.CharField(blank=True, choices=[('स्टोरीज', 'स्टोरीज'), ('एनालिसिस', 'एनालिसिस'), ('लाइफस्टाइल', 'लाइफस्टाइल'), ('अन्य', 'अन्य')], default='अन्य', help_text='Category for article', max_length=95),
        ),
        migrations.AlterField(
            model_name='article_hindi',
            name='category_english',
            field=models.CharField(blank=True, choices=[('Stories', 'Stories'), ('Analysis', 'Analysis'), ('Lifestyle', 'Lifestyle'), ('Other', 'Other')], default='अन्य', help_text='Category for article', max_length=95),
        ),
        migrations.CreateModel(
            name='Blog_visitor_hindi_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
                ('article_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article_hindi')),
            ],
        ),
    ]
