# Generated by Django 3.1.4 on 2021-01-15 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20210115_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_hindi',
            name='username',
        ),
        migrations.AddField(
            model_name='article_hindi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
