# Generated by Django 3.1.4 on 2021-01-16 13:42

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210115_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_hindi',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.hindi_post_image_path),
        ),
        migrations.AddField(
            model_name='article_hindi',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.hindi_post_image_path),
        ),
    ]
