# Generated by Django 3.1.4 on 2021-01-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210116_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_hindi',
            name='icon_image',
        ),
        migrations.RemoveField(
            model_name='article_hindi',
            name='thumbnail_image',
        ),
    ]
