# Generated by Django 3.1.4 on 2021-01-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_User',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=213)),
                ('email', models.CharField(max_length=213)),
                ('subject', models.CharField(max_length=213)),
                ('matter', models.CharField(max_length=513)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IP_visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=213, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=213, null=True)),
                ('sno', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
